version: '3.8'

services:
  mysql:
    image: mysql:latest
    restart: always
    env_file: ./.env
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: test_database
      MYSQL_USER: manh
      MYSQL_PASSWORD: not_root_password

  phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_USER: manh
      MYSQL_PASSWORD: not_root_password
    ports:
      - "8080:80"